export const RECYCLE_TOKEN_CONTRACT = import.meta.env.VITE_RECYCLE_TOKEN_CONTRACT_ADDRESS
export const RECYCLE_CONTRACT = import.meta.env.VITE_RECYCLE_CONTRACT_ADDRESS
export const ADMIN_ADDRESS = import.meta.env.VITE_ADMIN_ADDRESS